[[articles]]
title = "ãƒˆãƒ©ãƒ³ãƒ—ã®ã‚«ãƒ¼ãƒ‰ã¯Entityã‹ValueObjectã‹"
slug = "entity-vs-value-object"
tags = ["Design"]
published = true
published_at = "2024-5-20"
updated_at = "2024-5-20- 2:15"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "è‡ªåˆ†ã‚’æ£šå¸ã™"
published = true
published_at = "2024-5-10"
slug = "inventory-myself"
tags = ["ãƒã‚¨ãƒ "]
updated_at = "2024-5-10- 22:17"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "Cannot set LC_XXX to default locale: No such file or directoryã‚’è§£æ±ºã™ã‚‹"
published_at = "2023-10-6"
published = true
slug = "fix-vim-lc"
tags = ["vim"]
updated_at = "2024-5-2- 17:28"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "2023å¹´ã‚’æŒ¯ã‚Šè¿”ã‚‹"
published_at = "2023-9-4"
published = true
slug = "look-back-on-2023"
tags = ["ãƒã‚¨ãƒ "]
updated_at = "2024-5-2"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "ãƒ“ã‚¸ãƒ¥ã‚¢ãƒ«ã‚·ãƒ³ã‚«ãƒ¼è„³ã®ã‚†ã‚‹è¨€èªå­¦ãƒ©ã‚¸ã‚ªã‚’èã„ãŸ"
published_at = "2024-4-22"
published = true
slug = "visual-thinker"
tags = ["ãƒã‚¨ãƒ "]
updated_at = "2024-4-26"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "è‚²ä¼‘ã‚’åŠå¹´é–“å–ã‚Šã¾ã—ãŸ"
published_at = "2024-3-13"
published = true
slug = "paternity-leave"
tags = ["ãƒã‚¨ãƒ "]
updated_at = "2024-5-2"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "Arc Browserã®boostã§kintone JS APIã‚’ç„¡ç†ã‚„ã‚Šæ‰±ã†"
published_at = "2023-8-4"
published = true
slug = "how-to-use-object-in-arc-boost"
tags = ["Arc"]
updated_at = "2023-8-16"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "USã‚­ãƒ¼ãƒœãƒ¼ãƒ‰ã§ã‹ãªå…¥åŠ›æ™‚ã®é…åˆ—ã‚’macã¨winã§æƒãˆã‚‹æ–¹æ³•"
published_at = "2023-4-13"
published = true
slug = "share-us-keyboard-using-kana"
tags = ["keyboard", "è«–ç†é…åˆ—"]
updated_at = "2023-4-17"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "Vivaldiã®æ•‘å‡ºæ–¹æ³•"
published_at = "2023-3-6"
published = true
slug = "fix-vivaldi-brawser"
tags = ["Vivaldi"]
updated_at = "2023-4-16"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "HHKBã‹ã‚‰Moonlanderã«ä¹—ã‚Šæ›ãˆãŸ"
published_at = "2023-3-3"
published = true
slug = "introduce-moonlander"
tags = ["Moonlander", "keyboard", "é–‹ç™ºç’°å¢ƒ"]
updated_at = "2023-3-7"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "iPadã ã‘ã§ãƒ—ãƒ­ã‚°ãƒ©ãƒŸãƒ³ã‚°ç’°å¢ƒã‚’æ•´ãˆãŸè©±[VPS+Coder]"
published_at = "2021-7-2"
published = true
slug = "programming-with-coder"
tags = ["iPad", "é–‹ç™ºç’°å¢ƒ"]
updated_at = "2023-2-14"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "codespacesã§astroã‚’ä½¿ã†ã¨ãã¯é–‹ç™ºç’°å¢ƒã®ç«‹ã¡ä¸Šã’ã«â€”hostã‚’ã¤ã‘ã‚ˆã†"
published_at = "2023-2-13"
published = true
slug = "astro-host-in-codespaces"
tags = ["Astro", "Codespaces"]
updated_at = "2023-2-13"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "NotionWebClipperã§ä¿å­˜ã—ãŸè¨˜äº‹ã‚’ãƒ–ãƒ­ã‚°ã«å…¬é–‹ã—ãŸ"
published_at = "2023-2-8"
published = true
slug = "publish-my-links"
tags = ["Notion", "å€‹äººé–‹ç™º"]
updated_at = "2023-2-12"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "tsã§typeã‚’&ã§ç¹‹ãã¨neverå‹ã«ãªã£ã¦ã—ã¾ã£ãŸè©±"
published_at = "2023-1-9"
published = true
slug = "ts-type-param-cannot-override"
tags = ["TypeScript", "å€‹äººé–‹ç™º"]
updated_at = "2023-1-13"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "ã‚¢ã‚½ã‚·ã‚¨ãƒ¼ã‚·ãƒ§ãƒ³åˆ†æãŒã§ãã‚‹APIã®è©±"
published_at = "2023-1-27"
published = true
slug = "create-association-analysis-api"
tags = ["Aws", "Python", "å€‹äººé–‹ç™º"]
updated_at = "2023-8-29"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "Next.jsè£½ã®ãƒ–ãƒ­ã‚°ã®å†…éƒ¨æ§‹æˆã‚’æ›´æ”¹ã—ãŸ"
published_at = "2023-1-11"
published = true
slug = "upgrade-directory-structure"
tags = ["Nextjs", "Notion", "å€‹äººé–‹ç™º"]
updated_at = "2023-1-31"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "2023å¹´ã®æŠ±è² "
published_at = "2023-1-1"
published = true
slug = "resolution-2023"
tags = ["ãƒã‚¨ãƒ "]
updated_at = "2023-1-11"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "2022å¹´ã‚’æŒ¯ã‚Šè¿”ã‚‹"
published_at = "2022-12-29"
published = true
slug = "look-back-on-2022"
tags = ["ãƒã‚¨ãƒ "]
updated_at = "2023-1-11"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "iPadã§ãƒ—ãƒ­ã‚°ãƒ©ãƒŸãƒ³ã‚°é–‹ç™ºç’°å¢ƒæ§‹ç¯‰ã®åŠªåŠ›ã¨2023-å€‹äººçš„ãƒ™ã‚¹ãƒˆãƒ—ãƒ©ã‚¯ãƒ†ã‚£ã‚¹[Blink+VSCode+Codespaces]"
published_at = "2022-12-19"
published = true
slug = "coding-with-ipad"
tags = ["Blink", "Codespaces", "VSCode", "iPad", "é–‹ç™ºç’°å¢ƒ"]
updated_at = "2023-2-14"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "sudoæ¨©é™ã§ãƒªãƒ€ã‚¤ãƒ¬ã‚¯ãƒˆå‡¦ç†ã‚’è¡Œã£ã¦ãƒ•ã‚¡ã‚¤ãƒ«ã«æ›¸ãè¾¼ã‚€æ–¹æ³•"
published_at = "2022-12-13"
published = true
slug = "redirect-with-sudo"
tags = ["Shell"]
updated_at = "2022-12-13"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "ã‚ˆãä½¿ã†é–‹ç™ºç’°å¢ƒæ§‹æˆã‚’ï¼‘ã‚³ãƒãƒ³ãƒ‰ã§ä½œæˆã§ãã‚‹ã‚ˆã†ã«ã—ãŸ"
published_at = "2022-12-12"
published = true
slug = "setup-develop-environment"
tags = ["Docker", "å€‹äººé–‹ç™º"]
updated_at = "2022-12-12"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "Pythonã§DIã‚’å®Ÿè£…ã™ã‚‹"
published_at = "2022-11-28"
published = true
slug = "di-with-python"
tags = ["DI", "Python"]
updated_at = "2022-12-1"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "ä¾¿åˆ©ãªGitã‚³ãƒãƒ³ãƒ‰è¦šæ›¸"
published_at = "2022-11-12"
published = true
slug = "useful-git-command"
tags = ["git"]
updated_at = "2023-2-28"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "Reactã®ãƒ¬ãƒ³ãƒ€ãƒªãƒ³ã‚°é †ã«ã¤ã„ã¦"
published_at = "2022-5-26"
published = true
slug = "react-rendering-sequence"
tags = ["React"]
updated_at = "2023-2-13"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "Google Driveå†…ã®ç”»åƒã«ç›´æ¥ã‚¢ã‚¯ã‚»ã‚¹ã§ãã‚‹URLã®ä½œæˆæ–¹æ³•"
slug = "google-drive-url-directly"
tags = ["GoogleDrive"]
published = true
published_at = "2022-5-12"
updated_at = "2022-12-12"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "ç‰‡é“2æ™‚é–“åŠè¶…ãˆã®è¶…é•·è·é›¢é€šå‹¤ã‚’ï¼‘å¹´åŠé ‘å¼µã£ã¦ãŸæ™‚ã®è©±"
slug = "long-distance-commutation"
tags = ["Work-Life Balance", "ãƒã‚¨ãƒ "]
published = true
published_at = "2021-7-2"
updated_at = "2023-1-1"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "URIãƒ©ã‚¤ã‚¯ãªæ–‡å­—åˆ—ã§æ”¹è¡Œã—ã¦ãã‚Œãªã„ã¨ãã®cssã®å……ã¦æ–¹"
slug = "new-line-css-for-uri-like-string"
tags = ["CSS", "HTML", "å€‹äººé–‹ç™º"]
published = true
published_at = "2022-3-29"
updated_at = "2023-3-7"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicudata.69.dylib ã§å‹•ã‹ãªããªã£ãŸmacã®PHPã‚’æ•‘å‡ºã—ãŸ"
slug = "library-icu4c-not-found"
tags = ["Mac", "PHP"]
published = true
published_at = "2022-3-28"
updated_at = "2022-12-12"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "notion API + NEXT.js + netlify ã§ãƒ–ãƒ­ã‚°ç«‹ã¡ä¸Šã’ â‘¦ å‹•çš„OGP"
slug = "build-blog-using-notion-api-7"
tags = ["Netlify", "Nextjs", "Notion", "å€‹äººé–‹ç™º"]
published = true
published_at = "2022-3-15"
updated_at = "2024-5-2"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "notion API + NEXT.js + netlify ã§ãƒ–ãƒ­ã‚°ç«‹ã¡ä¸Šã’ â‘¥ SEOé–¢é€£ã®è¨­å®š"
slug = "build-blog-using-notion-api-6"
tags = ["Netlify", "Nextjs", "Notion", "å€‹äººé–‹ç™º"]
published = true
published_at = "2022-3-11"
updated_at = "2024-5-2"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "notion API + NEXT.js + netlify ã§ãƒ–ãƒ­ã‚°ç«‹ã¡ä¸Šã’ â‘¤ ç”»é¢ä½œæˆ"
slug = "build-blog-using-notion-api-5"
tags = ["Netlify", "Nextjs", "Notion", "å€‹äººé–‹ç™º"]
published = true
published_at = "2022-2-13"
updated_at = "2024-5-2"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "notion API + NEXT.js + netlify ã§ãƒ–ãƒ­ã‚°ç«‹ã¡ä¸Šã’ â‘£ ChakraUIã®ãŠå‹‰å¼·"
slug = "build-blog-using-notion-api-4"
tags = ["ChakraUI", "Netlify", "Nextjs", "Notion", "å€‹äººé–‹ç™º"]
published = true
published_at = "2022-2-13"
updated_at = "2024-5-2"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "DockerImageã®Composerã‚’åˆ©ç”¨ã—ã¦çªå¦‚ã‚¨ãƒ©ãƒ¼ãŒå‡ºã‚‹ã‚ˆã†ã«ãªã£ãŸ"
slug = "error-in-composer-docker-image"
tags = ["Composer", "Docker", "PHP"]
published = true
published_at = "2022-3-28"
updated_at = "2023-1-1"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "notion API + NEXT.js + netlify ã§ãƒ–ãƒ­ã‚°ç«‹ã¡ä¸Šã’ â‘¢  NEXT.jsã®ãŠå‹‰å¼·"
slug = "build-blog-using-notion-api-3"
tags = ["Netlify", "Nextjs", "Notion", "å€‹äººé–‹ç™º"]
published = true
published_at = "2022-3-20"
updated_at = "2022-12-12"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "æ›¸ç±[èã‘ã‚‹ãƒ‡ã‚¶ã‚¤ãƒ³]ã‹ã‚‰å­¦ã‚“ã ã“ã¨"
slug = "what-to-learn-by-reading-natural-design"
tags = ["Book", "Design", "Learning"]
published = true
published_at = "2022-3-18"
updated_at = "2022-12-12"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "æ›¸ç± [ãƒ‰ãƒ¡ã‚¤ãƒ³é§†å‹•è¨­è¨ˆå…¥é–€] ã‹ã‚‰å­¦ã‚“ã ã“ã¨"
slug = "what-to-learn-by-reading-ddd"
tags = ["Book", "DDD", "Learning"]
published = true
published_at = "2022-3-18"
updated_at = "2022-12-12"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "æ›¸ç±[ãƒªãƒ¼ãƒ€ãƒ–ãƒ«ã‚³ãƒ¼ãƒ‰] ã‹ã‚‰å­¦ã‚“ã ã“ã¨"
slug = "what-to-learn-by-reading-readable-code"
tags = ["Book", "Learning"]
published = true
published_at = "2022-3-18"
updated_at = "2022-12-12"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "notion API + NEXT.js + netlify ã§ãƒ–ãƒ­ã‚°ç«‹ã¡ä¸Šã’ â‘¡ notion apiç¢ºèª"
slug = "build-blog-using-notion-api-2"
tags = ["Netlify", "Nextjs", "Notion", "å€‹äººé–‹ç™º"]
published = true
published_at = "2022-1-18"
updated_at = "2022-12-12"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "notion API + NEXT.js + netlify ã§ãƒ–ãƒ­ã‚°ç«‹ã¡ä¸Šã’ â‘ "
slug = "build-blog-using-notion-api-1"
tags = ["Netlify", "Nextjs", "Notion", "å€‹äººé–‹ç™º"]
published = true
published_at = "2022-1-18"
updated_at = "2022-12-12"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "ãƒ–ãƒ­ã‚°ä½œã‚Šã¾ã—ãŸğŸ‘‹"
slug = "hello-world"
tags = ["ãƒã‚¨ãƒ "]
published = true
published_at = "2022-3-20"
updated_at = "2023-1-11"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"

[[articles]]
title = "_typography"
slug = "typography"
cover = "https://images.unsplash.com/photo-1511548774318-563182fe8d03?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=6000"
tags = ["å€‹äººé–‹ç™º"]
published = true
published_at = "2022-2-11"
updated_at = "2024-5-30"

